PizzaLover's pizzaPad
hackclub/hackpad pull request #130
Opened 2024-10-20 14:45 UTC by pizzalover125

pizzaPad!!!! The one and only pizzaPad!

2024-10-23 03:42 UTC, qcoral requested changes
Hey - awesome submission, couple things:
- I need the source files for the pcb, could you upload a schematic?
- The case needs to be broken into 3D printable parts
- I need screws in the BOM

2024-10-24 00:34 UTC, pizzalover125 commented
Hello! I updated the BOM and added the part-by-part step files. However, for the PCB, EasyEDA only has the PCB.json export. The only other option is the PDFs, which I have provided.

2024-10-26 00:33 UTC, qcoral approved these changes
nice job, but the vcc and gnd pins are flipped for your OLED footprint - can you fix that?

2024-10-26 00:33 UTC, qcoral requested changes
meant to request changes whoops

2024-10-26 00:36 UTC, pizzalover125 commented
wait, do I need to import new footprint, or can I just flip them intentionally wrong (right for you)?

2024-10-26 05:55 UTC, qcoral commented
The latter should work, make sure to reroute your pcb!

2025-02-16 20:22 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have a different structure this time around so be sure to follow the submission guidelines!

2025-02-16 20:22 UTC, closed without merging

2025-02-16 22:09 UTC, pizzalover125 commented
What is the different structure?