Guerriacanpad
hackclub/hackpad pull request #136
Opened 2024-10-20 19:38 UTC by Guerriacan

Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

2024-10-23 03:00 UTC, Dongathan-Jong commented
Hey! Your case design is a little unprintable, we don't like supports! if you could chop off the front so that the plate for the switches is flush to the bed, that would be printable!

2024-10-23 16:31 UTC, Guerriacan commented
Just realized there's an issue with the I/O extender i'm using, i'll fix it

2024-10-23 20:15 UTC, Guerriacan commented
Everything should be fixed now, let me know if something is missing !

2024-10-28 23:46 UTC, M0HID requested changes
Hey there! It looks like your PCB uses SMD hotswap sockets but there aren't any included in your BOM. Could you please update either the footprint or the BOM to let us know how you're planning to connect the switches to the PCB?

2025-02-16 20:23 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have a different structure this time around so be sure to follow the submission guidelines!

2025-02-16 20:23 UTC, closed without merging