Hackpad
hackclub/hackpad pull request #193
Opened 2024-10-21 22:22 UTC by GaoYeGithub

There likely something I'm not getting however the example and the tutorial https://hackpad.hackclub.com/submitting is very different.

2024-10-23 02:43 UTC, jpt1729 approved these changes
looks good to me!

https://github.com/hackclub/hackpad/pull/7

2024-10-23 17:43 UTC, M0HID requested changes
Nice work so far! Could you add your source KiCad files to the PCB folder so I can review it please?

2024-10-23 18:41 UTC, qcoral requested changes
awesome start - i need the pcb source files though!

2024-10-24 13:10 UTC, GaoYeGithub commented
Oh like the .sch one?

2024-10-25 00:50 UTC, qcoral commented
.pro, .sch. etc - all of it!

2024-10-25 01:47 UTC, GaoYeGithub commented
Is this all I need?

2024-10-25 09:27 UTC, M0HID commented
![image](https://github.com/user-attachments/assets/e95e51aa-4079-4654-9ac6-cd370a1d70f7)
Hey - You have some extra holes drilled here, is that intentional?

2024-10-25 23:30 UTC, qcoral approved these changes
awesome job on the pcb changes, but the case files seem to be messed up - can you break them up into printable stl files?

2024-10-27 11:58 UTC, 0CODERKID commented
The firmware does not contain anything , you should have the basic code set up...

2025-02-09 03:00 UTC, closed without merging