Chemistry narwhal hackpad
hackclub/hackpad pull request #209
Opened 2024-10-22 02:13 UTC by ChemistryNarwhal

Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

2024-10-23 20:26 UTC, blazecoding2009 requested changes
Would you mind please putting your files in a separate folder? Currently they're in the root hackpads directory. Thanks!

2024-10-23 21:06 UTC, ChemistryNarwhal commented
Hi!

I am just out right now. I will do that as soon as I get home.

Ariane


On Wed, Oct 23, 2024, 4:26 p.m. blaze ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Would you mind please putting your files in a separate folder? Currently
> they're in the root hackpads directory. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hackpad/pull/209#pullrequestreview-2390423244>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AND3UZQTYSJA3Z4RCIEWH4TZ5AA7ZAVCNFSM6AAAAABQLNDLL2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJQGQZDGMRUGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-24 22:40 UTC, ChemistryNarwhal commented
Hi just added a message to the slack. I'm Having some trouble on figuring out how to fix it. I'll get the problem solved as soon as I can.

2024-10-25 09:38 UTC, M0HID commented
Hey - could you also add your source KiCad files to the PCB folder? I've fixed your file structure for you, everything needs to be in the hackpads/ChemistryNarwhalHackpad folder

2025-02-16 20:23 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have a different structure this time around so be sure to follow the submission guidelines!

2025-02-16 20:23 UTC, closed without merging