Trains's macropad!
hackclub/hackpad pull request #229
Opened 2024-10-22 03:58 UTC by i-like-trains72

Ready to submit your project? Nice job! Hopefully you've read the [submission guidelines](https://hackpad.hackclub.com/submitting). **If not, make sure to read them first.**

If you're unsure about the format, make sure to check out the [Orpheuspad example](insertexample) and follow the format there.

If this PR isn't a submission, that's okay too! If there's anything about this PR template that seems confusing, let me know in #hackpad on the slack!

2024-10-22 03:58 UTC, i-like-trains72 commented
I made this on a different repository that was not a fork, so I'm currently just going to the root and doing all of it manually. Please let me do this!

2024-10-22 04:05 UTC, i-like-trains72 commented
should be good, try again?

2024-10-27 05:16 UTC, BrightTheBackpack requested changes
cool hackpad!
Could you make sure you file structure is
hackpad
	-hackpads
		-macropadname
			-pcb
			-cad
			-whatever other files and folders
could you also make sure to upload  all the individual files for each part of the case?

2025-02-16 20:24 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have a different structure this time around so be sure to follow the submission guidelines!

2025-02-16 20:24 UTC, closed without merging