Grasspad
hackclub/hackpad pull request #240
Opened 2024-10-22 04:19 UTC by IM-THE-GRASS

I didn't have enough time to make the firmware because its taking forever to download and stuff (and i had a math test today so i didn't do it earlier 😭) BUT I will try and update it in the future with the firmware

2024-10-22 04:32 UTC, IM-THE-GRASS commented
i have to go to sleep broo i dont think ill finish the firmware today 😭 
why does QMK take so long????

2024-10-23 21:38 UTC, qcoral requested changes
hey - no worries about the firmware, just try and get it in ASAP. Request a review once you add it!

2024-10-26 00:09 UTC, qcoral requested changes
This is awesome, but I need the case to be broken up into separate STL files. Can you look over hackpad.hackclub.com/submitting and let me know how it goes?

2025-01-31 02:04 UTC, IM-THE-GRASS commented
@qcoral i fixed the firmware and hackpad v2 is out so now will u merge it plss 🥺

2025-01-31 02:24 UTC, IM-THE-GRASS commented
btw dont worry about printing the case, i have a 3d printer and im going to print it myself

2025-01-31 22:07 UTC, IM-THE-GRASS commented
ok im making a new pr this one isnt going anywhere

2025-01-31 22:07 UTC, closed without merging