Slackpad by Muhammad :)
hackclub/hackpad pull request #294
Opened 2024-10-25 13:21 UTC by Babyyoda777

Hi, this is my slackpad! Just wanted to ask, do we get only one and are we allowed to request spare components (e.g. spare keycaps and switches) since they often come in bulk anyways?

Thanks!

2024-10-25 13:31 UTC, M0HID commented
Hey there! It looks like you're missing a few files, could you please add your KiCad files and the gerber files with the production folder to the PR please?

2024-10-25 13:39 UTC, Babyyoda777 commented
> Hey there! It looks like you're missing a few files, could you please add your KiCad files and the gerber files with the production folder to the PR please?

Hi, I used Easyeda and not KiCad, the source files for them are already there. I just added the gerbers as well!

2024-10-25 13:57 UTC, Babyyoda777 commented
Ok all sorted @M0HID :)

2024-10-25 23:55 UTC, qcoral requested changes
Could you include a pdf of the schematic and also break the case up into an STL(s?) that I can 3D print? thanks!

2024-10-26 14:49 UTC, Babyyoda777 commented
> Could you include a pdf of the schematic and also break the case up into an STL(s?) that I can 3D print? thanks!

Yep all done, pdf is in pub section and stls are in cad folder.

2025-02-16 20:26 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have a different structure this time around so be sure to follow the submission guidelines!

2025-02-16 20:26 UTC, closed without merging