Resubmitting hackpad to fix pcb issue
hackclub/hackpad pull request #336
Opened 2024-12-11 20:25 UTC by CodrOfTheFuture

Hi, for the reviewer please look at my gerbers and pcb very carefully because I got problems with the design (or gerber file) stated by the manufacturer. If possible please check the gerber file using a gerber viewer (KiCad has one). Thanks!

2024-12-11 20:32 UTC, pmnlla commented
Will have a look ASAP.

2024-12-11 20:46 UTC, pmnlla commented
Gerbers appear to still be problematic. I suggest you export from KiCad again using the Fabrication Toolkit plugin.

![{FDE3A689-5FAC-4374-8F33-CFF7BF0DDF0D}](https://github.com/user-attachments/assets/60d8cb9e-91a3-44e2-953d-284c98029af8)

2024-12-11 20:49 UTC, pmnlla commented
There are 3 unconnected item errors in your PCB. I suggest you fix them before the PCB is sent to production and one of your keys ends up broken lul
![{D4EF5258-D19F-4870-A252-A851965DFDA4}](https://github.com/user-attachments/assets/f819f667-c2b9-4e39-b169-3c20581afcd2)

2024-12-11 21:00 UTC, pmnlla requested changes
Gerber file is invalid, PCB has 3 unconnected item errors in DRC. A few quick fixes and you'll be on your way!

2025-02-16 20:28 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have a different structure this time around so be sure to follow the submission guidelines!

2025-02-16 20:28 UTC, closed without merging