ChicPad request
hackclub/hackpad pull request #59
Opened 2024-10-12 18:56 UTC by Atishay-Bhati

Ready to make a PR? Great! Make sure your directory structure looks like this:

├── CAD \
│   ├── case.stl \
│   └── plate.dxf \
├── firmware \
│   └── rp2040.bin \
└── PCB \
    ├── macropad.pro \
    └── macropad.sch 

(The file names do not matter, just the folders)

2024-10-21 21:41 UTC, Dongathan-Jong commented
Hey! You are super close! Currently we are using through-hole RP2040 XIAOs. Your footprint for the XIAO will short with the encoder pads. Also, please request screws in your BOM!

2024-10-26 18:19 UTC, Atishay-Bhati commented
Hi! Which footprint should I use for the XIAO? Also how many screws? Not really sure about that.

2024-10-26 18:27 UTC, souptik-samanta requested changes
you would need to move the xaio a bit as @Dongathan-Jong told it would short

2024-10-28 23:58 UTC, M0HID requested changes
Could you update your PCB and also add your schematic to the PR please?

2025-02-16 20:20 UTC, Dongathan-Jong commented
Hey! Hackpad V2 is on, check it out [here](https://hackpad.hackclub.com/). I will be closing this PR since it is not a part of the V2 submission, you are welcome to resubmit, but we have different submission rules.

2025-02-16 20:20 UTC, closed without merging