nimitpad
hackclub/hackpad pull request #65
Opened 2024-10-13 13:59 UTC by NimitVijayvargee

nimitpad
PCB - White
Case - Prusament Lime

2024-10-22 16:59 UTC, M0HID requested changes
Hi, your Hackpad is almost done except it's missing a .DXF file for the laser cut acrylic. Could you add that to the CAD folder please?

2024-10-22 17:28 UTC, NimitVijayvargee commented
Hey! Thanks for the info, but there is a laser cutting SVG file with the case. Please check

2024-10-22 23:09 UTC, qcoral requested changes
The attached SVG doesn't seem to work for me, can you try exporting it again (preferably in DXF)? Tested with adobe illustrator, figma, and fusion360

2024-10-30 08:43 UTC, NimitVijayvargee commented
Updated cover to be a working SVG file, please check. 
If DXF is required, please let me know.

2025-02-15 16:35 UTC, closed without merging